---
  - name: Installs nginx web server
    apt: name=nginx state=present
    notify:
      - start nginx

  - name: nginx configuration
    template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default
    notify:
      - restart php5-fpm
      - restart nginx