---
- hosts: all
  sudo: yes

  roles: 
    - { role: common, tags: [common] }
    - { role: users, tags: [users] }
    - { role: sshd, tags: [sshd] }
    - { role: nginx, tags: [nginx] }
    - { role: mariadb, tags: [mariadb] }
    - { role: php, tags: [php] }